quarkus:
  http:
    port: 8080
    test-port: 8181
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:default
  hibernate-orm:
    sql-load-script: import.sql
    database:
      generation: drop-and-create
  kubernetes:
    deploy: false #true to deploy automatically
    kubernetes-client.trust-certs: true
    deployment-target: knative
  container-image:
    builder: s2i # docker or jib
    group: geoand # set the Kubernetes namespace which will be used to run the application
    registry: image-registry.openshift-image-registry.svc:5000 # set the container image registry - this is the standard URL used to refer to the internal OpenShift registry
  openshift:
    namespace: redcat-opensphere
    route:
      expose: true